name: Debug

on:
  workflow_dispatch:
    inputs:
      latest:
        description: 'Latest'
        required: true
        type: boolean
      tags:
        description: 'Tags'
        required: true
        type: string

jobs:
  publish_image:
    name: Read GitHub metadata
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Hello world"
          echo ${{ inputs.latest }} 
          echo ${{ inputs.tags }} 
